FROM faucet/python3:5.0.1

COPY ./ /pipette-src/

RUN apk add gcc g++ python3-dev musl-dev py3-pip && \
        pip3 install -r pipette-src/requirements.txt && \
        apk del gcc python3-dev musl-dev

EXPOSE 6653

CMD ["ryu-manager", "/pipette-src/pipette.py"]
