FROM faucet/python3:9.0.0

COPY ./ /pipette-src/

RUN apk add gcc g++ git python3-dev musl-dev py3-pip && \
        pip3 install -r pipette-src/requirements.txt && \
        apk del gcc git python3-dev musl-dev

EXPOSE 6653

CMD ["osken-manager", "/pipette-src/pipette.py"]