FROM ubuntu:20.04

RUN apt-get update && \
  apt-get -y --no-install-recommends install openvswitch-common openvswitch-switch iproute2 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY configureovs.sh /configureovs.sh
ENTRYPOINT ["/configureovs.sh"]
